// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"webook/webook/internal/repository"
	"webook/webook/internal/repository/cache/Redis"
	"webook/webook/internal/repository/dao"
	"webook/webook/internal/service"
	"webook/webook/internal/web"
)

// Injectors from wire.go:

func InitApp() *gin.Engine {
	cmdable := InitRedis()
	v := InitGinMiddlewares(cmdable)
	db := InitDB()
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCacheCodeRepository(codeCache)
	smsService := InitSMSService()
	codeService := service.NewSmsCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService)
	engine := InitGinServer(v, userHandler)
	return engine
}
